### ISSUE TITLE
Simulation Design in uniBrain-Speller/StimulationSystem/StimulationProcess /StimulationController.py

### ISSUE THREAD

**Issue by Gpandaa** [THU-BCI/uniBrain-Speller#1]
StimulationController类的loadPics中，visual.ElementArrayStim对象每帧对应颜色计算公式brightness = 0.5 + 0.5 * math.sin( 2 * math.pi * rect.frequency /config.refreshRate * (N-1) + rect.start_phase )，brightness取值范围[0,1]。但是visual.ElementArrayStim在’rgb‘的colorspace内取值范围是[-1,1]，意味着最后呈现的刺激是'灰[0,0,0]白[1,1,1]'闪烁，请问这是特意设计的吗？但是《Conformal in-ear bioelectronics for visual and auditory brain-computer interfaces》论文附件视频中实验刺激好像是普通的黑白闪烁刺激？

**Comment by kenttkh** [comment]
最终输出就是普通的黑白，测试结果也是这样，你可以试试跑看看。
